remote_theme: ISSAE/architect

name: MongoDB Tutorial

author: Vera Mawla

author_email: veramawla@gmail.com

title: MongoDB Tutorial
google_analytics: UA-29708002-2

plugins:
  - jekyll-sitemap

theme: jekyll-theme-merlot